# escape=`
FROM microsoft/nanoserver:10.0.14393.1593

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Pages" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ADD release\drone-gh-pages.exe c:\drone-gh-pages.exe
ENTRYPOINT [ "c:\\drone-gh-pages.exe" ]
